baseURL = 'https://manweiliu.github.io'
title = 'Manwei Liu'
languageCode = "en"
languageName = "English"
hasCJKLanguage = true
enableEmoji = false
ignoreErrors = ["error-remote-getjson"]

[params]
  description = "Assistant professor of economics at Nanjing Audit University"
  scholar = "sDj6-O4AAAAJ&hl=en"

[markup]
  [markup.highlight]
    noClasses = false
